Repository fga-eps-mds/2023-1-schedula-front, pull requests merged in 2023-06, with the labels that each got.

#33 #90 edicao exclusao atendimentos
  src/features/issues/api/delete-issue.ts
  src/features/issues/api/types.ts
  src/features/issues/components/issue-item/index.tsx
  src/features/issues/components/issue-item/issue-item.spec.tsx
  src/pages/chamados/index.tsx
Labels: enhancement

#35 Develop
  package.json
  src/components/layout/default-layout-open.tsx
  src/components/side-bar-open/index.tsx
  src/components/side-bar-open/sidebar-open.spec.tsx
  src/config/routes/Routes.tsx
  src/features/issues/api/delete-issue.ts
  src/features/issues/api/types.ts
  src/features/issues/components/issue-item/index.tsx
  src/features/issues/components/issue-item/issue-item.spec.tsx
  src/features/schedules/components/schedule-item-open/index.tsx
  src/features/tutorials/components/tutorial-form/index.tsx
  src/features/tutorials/components/tutorial-modal/index.tsx
  src/features/workstations/components/workstation-form/index.tsx
  src/pages/agendamentos_abertos/index.tsx
  src/pages/chamados/index.tsx
  src/pages/login/index.tsx
  src/pages/login/login.spec.tsx
  src/utils/toast.spec.tsx
  yarn.lock
Labels: enhancement

#37 #98 bug descricao agendamentos
  src/features/schedules/components/schedule-item/index.tsx
  src/features/schedules/components/schedule-item/schedule-item.spec.tsx
Labels: bug

#40 #109 ordenacao atendimentos
  src/pages/chamados/chamados.spec.tsx
  src/pages/chamados/index.tsx
Labels: enhancement

#45 #113 categorias tipos problema usuario externo
  src/components/forms/categoria-form/categoria-form.spec.tsx
  src/features/problem/api/types.ts
  src/features/problem/problem-categories/components/categoria-form/index.tsx
  src/features/problem/problem-categories/components/category-modal/category-modal.tsx
  src/features/problem/problem-types/api/types.ts
  src/features/problem/problem-types/components/problem-type-form/index.tsx
  src/features/problem/problem-types/components/problem-type-modal/index.tsx
  src/features/problem/problem-types/types.ts
  src/pages/categorias/categories.spec.tsx
  src/pages/categorias/index.tsx
  src/types/categoria.d.ts
Labels: bug, enhancement

#46 #101 #110 Ajusta a edição de Agendamento e cor de status
  src/features/schedules/components/schedule-edit-modal/index.tsx
  src/features/schedules/components/schedule-item/index.tsx
  src/pages/agendamentos/index.tsx
  src/utils/format-date.spec.tsx
  src/utils/format-date.ts
Labels: bug

#49 #114 bug edicao tutorial
  src/features/tutorials/components/tutorial-form/index.tsx
  src/pages/gerenciar-tutorial/index.tsx
  src/pages/tutoriais/index.tsx
Labels: bug

#44 #104 Fix: Limit description field
  src/features/schedules/components/schedule-edit-form/index.tsx
  src/features/schedules/components/schedule-edit-modal/index.tsx
  src/features/schedules/components/schedule-form/index.tsx
Labels: bug

#51 #41 #42 notificacoes
  src/components/form-fields/input/index.tsx
  src/components/side-bar/index.tsx
  src/components/side-bar/sidebar-notification/index.tsx
  src/components/side-bar/sidebar.spec.tsx
  src/config/routes/Routes.tsx
  src/constants/alertas.ts
  src/constants/requests.ts
  src/contexts/AuthContext.tsx
  src/features/alerts/api/delete-alerts.tsx
  src/features/alerts/api/detele-alerts.tsx
  src/features/alerts/api/get-all-alerts.tsx
  src/features/alerts/api/post-create-alerts.tsx
  src/features/alerts/api/types.tsx
  src/features/alerts/components/alert-delete-form/alert-delete-form.spec.tsx
  src/features/alerts/components/alert-delete-form/index.tsx
  src/features/alerts/components/alert-form/alert-form.spec.tsx
  src/features/alerts/components/alert-form/index.tsx
  src/features/alerts/components/alert-item-manager/index.tsx
  src/features/alerts/components/alert-item/alert-item.spec.tsx
  src/features/alerts/components/alert-item/index.tsx
  src/features/alerts/components/alert-modal/index.tsx
  src/features/alerts/components/delete-alert-modal/index.tsx
  src/features/alerts/constants/cache.tsx
  src/features/alerts/constants/requests.tsx
  src/features/alerts/type.tsx
  src/features/notifications/api/get-all-notifications.tsx
  src/features/notifications/api/put-update-notifications.tsx
  src/features/notifications/api/types.tsx
  src/features/notifications/components/notification-item/index.tsx
  src/features/notifications/components/notification-item/notification-item.spec.tsx
  src/features/notifications/components/notification-pendency-form/index.tsx
  src/features/notifications/components/notification-pendency-form/notification-pendency-form.spec.tsx
  src/features/notifications/components/notification-pendency-modal/index.tsx
  src/features/notifications/components/notification-solved-form/index.tsx
  src/features/notifications/components/notification-solved-form/notification-solved-form.spec.tsx
  src/features/notifications/constants/cache.tsx
  src/features/notifications/constants/requests.tsx
  src/features/notifications/types.tsx
  src/features/users/api/get-all-users.ts
  src/pages/notificacoes/index.tsx
  src/pages/notificacoes/notificacoes_admin/index.tsx
  src/pages/notificacoes/notificacoes_admin/notificacoes_admin.spec.tsx
  src/pages/notificacoes/notificacoes_usuario/index.tsx
  src/pages/notificacoes/notificacoes_usuario/notificacoes_usuario.spec.tsx
  src/types/alerta.d.ts
Labels: enhancement

#27 #78 fixing categorie editing and deletion bug
  src/features/categories-tutorial/api/get-all-categories-tutorial.ts
  src/features/tutorials/components/tutorial-form/index.tsx
  src/pages/categorias_de_tutorial/categorias_de_tutorial.spec.tsx
  src/pages/categorias_de_tutorial/index.tsx
Labels: bug
